# Launch tmux on start

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux"

window:
   dimensions:
     columns: 120
     lines: 40

font:
  normal:
    family: FiraCode Nerd Font Mono
    style: Regular

colors:
  primary:
    background: '#0F0F0F'
    foreground: '#F1F1F1'

  # Normal Colours
  normal:
    black:   '#1a1a1a'
    red:     '#f4005f'
    green:   '#98e024'
    yellow:  '#fa8419'
    blue:    '#9d65ff'
    magenta: '#f4005f'
    cyan:    '#58d1eb'
    white:   '#c4c5b5'

  # Bright Colours
  bright:
    black:   '#625e4c'
    red:     '#f4005f'
    green:   '#98e024'
    yellow:  '#e0d561'
    blue:    '#9d65ff'
    magenta: '#f4005f'
    cyan:    '#58d1eb'
    white:   '#f6f6ef'
